#!/bin/bash

# Determine the OS
# For UnitedLinux/SuSE/Novell Linux
# For RHEL/CentOS
# For other Linux, print an error and exit.

LSB_RELEASE_BIN=`which lsb_release 2>/dev/null`
if [ $? -eq 0 ]; then
	DEBUG echo "Found lsb_release"
else
	echo "Unable to find lsb_release"
	exit 1
fi

