#!/bin/bash

# define the debug function
_DEBUG=false
DEBUG ()
{
	  $_DEBUG && $@ || :
}

DRYRUN=false
MODE=""
PRODUCT=""
FORCE=false
FIX=false

usage()
{
	echo "Usage: install [--install] [--uninstall] [--product <informix|jsonListener>] [--debug] [--dryrun] [--force]"
}

while [ "$1" != "" ]; do
	case $1 in
	--debug ) _DEBUG=true
		;;
	--dryrun ) DRYRUN=true
		;;
	--install ) MODE="install"
		;;
	--uninstall ) MODE="uninstall"
		;;
	--verify ) MODE="verify"
		;;
	--fix ) FIX=true
		;;
	--product ) shift
		PRODUCT=$1
		;;
	--force ) FORCE=false
		;;
	--help ) usage;
		exit 0;;
	* ) usage;
		exit 1;;
	esac
	shift
done

if [ -z "$PRODUCT" ]; then
	echo -n "Enter the name of the product to install: "
	read response
	if [ -n "$response" ]; then
		PRODUCT="$response"
	else
		echo "No product specified. Exiting"
		exit 0
	fi
fi

if $_DEBUG; then echo "debug mode enabled"; fi
if $DRYRUN; then echo "dry run enabled"; fi

if [ -f "/etc/rc.d/init.d/functions" ]; then
	DEBUG echo "Detected RHEL"
	PLATFORM="RHEL"
elif [ -f /etc/rc.status ] ; then
	DEBUG echo "Detected SLES"
	PLATFORM="SLES"
else
	echo "Detected unsupported platform"
	exit 1
fi

# determine the path to the script in a POSIX-compliant manner
SCRIPT_PATH=`dirname "$0"`
SCRIPT_PATH=`eval "cd \"$SCRIPT_PATH\" && pwd"`
DEBUG echo "SCRIPT_PATH=$SCRIPT_PATH"

INFORMIX_INIT="${SCRIPT_PATH}/informix.suse"
INFORMIX_SYSCONFIG="${SCRIPT_PATH}/informix.sysconfig"
LISTENER_INIT="${SCRIPT_PATH}/jsonListener.init"
LISTENER_SYSCONFIG="${SCRIPT_PATH}/jsonListener.sysconfig"
INIT_DIR="/etc/init.d"
SBIN_DIR="/sbin"
SYSCONFIG_DIR="/etc/sysconfig"

# Determine the OS
# For UnitedLinux/SuSE/Novell Linux
# For RHEL/CentOS
# For other Linux, print an error and exit.

LSB_RELEASE_BIN=`which lsb_release 2>/dev/null`
if [ $? -eq 0 ]; then
	DEBUG echo "Found lsb_release"
else
	echo "Unable to find lsb_release"
	exit 1
fi

# Return Codes
#  0 - the argument is a directory and is writable
#  1 - the argument does not exist
#  2 - the argument exists, but is not a directory
#  3 - the argument exists, is a directory, but is not writable
canWriteToDir()
{
	if [ -d "$1" ]; then
		if [ -w "${1}" ]; then
			return 0
		else
			echo "Unable to write to ${1} (No write permission)"
			return 3
		fi
	else
		if [ -a "$1" ]; then
			echo "Unable to write to ${1} (File is not a directory)"
			return 2
		else
			echo "Unable to write to ${1} (File does not exist)"
			return 1
		fi
	fi
}

# Arguments
# $1 -- source path (the path to the file to copy)
# $2 -- target path (the path to copy the file to)
# $3 -- the mode to set the file to
# $4 -- the file ownership (chown)
# Return Codes
# 0 -- success
# 1 -- failure
copyFileTo()
{
	canWriteToDir `dirname ${2}`
	if [ $? -ne 0 ]; then
		if [ ! $FORCE ]; then exit 1; fi
	fi
	
	if $DRYRUN; then
		echo cp "${1}" "${2}"
		if [ -n $3 ]; then
			echo chmod $3 "${2}"
		fi
		if [ -n $4 ]; then
			echo chown $4 "${2}"
		fi
	else
		cp "${1}" "${2}"
		if [ -n $3 ]; then
			chmod $3 "${2}"
		fi
		if [ -n $4 ]; then
			chown $4 "${2}"
		fi
	fi
	return 0
}

# Arguments
# $1 -- the path to the file
# $2 -- the file mode
# $3 -- the file user
# $4 -- the file group
# Return Codes
# 0 -- success
# 1 -- the file does not exist
# 2 -- the file does not have the correct mode
# 3 -- the file does not have the correct owner
# 4 -- the file does not have the correct group
verifyFile()
{
	local count
	DEBUG echo "verifyFile $1 $2 $3 $4"
	if [ -f "${1}" ]; then
		# check the mode
		count=`find "${1}" -perm "${2}" | wc -l`
		if [ $count -eq 0 ]; then
			echo "File ${1} mode is incorrect"
			if $FIX; then
				chmod $2 "${1}"
			else
				return 2
			fi
		fi

		# check the user
		count=`find "${1}" -user "${3}" | wc -l`
		if [ $count -eq 0 ]; then
			echo "File ${1} ownership is incorrect"
			if $FIX; then
				chown $3 "${1}"
			else
				return 3
			fi
		fi

		# check the group
		count=`find "${1}" -group "${4}" | wc -l`
		if [ $count -eq 0 ]; then
			echo "File ${1} group is incorrect"
			if $FIX; then
				chgrp $4 "${1}"
			else
				return 4
			fi
		fi

		echo "Verified file ${1}"
		return 0
	else
		echo "File ${1} does not exist";
		return 1;
	fi
}

installInformix()
{
	installInitScript "informix" "${INFORMIX_INIT}"
	installSysconfigScript "informix" "${INFORMIX_SYSCONFIG}"

	case "${PLATFORM}" in
	'SLES') $DRYRUN || insserv informix;;
	'RHEL') $DRYRUN || chkconfig --add informix;;
	*) echo "Unsupported platform"; exit 1;;
	esac
}

uninstallInformix()
{
	uninstallInitScript "informix"
	uninstallSysconfigScript "informix"
}

installJsonListener()
{
	installInitScript "jsonListener" "${LISTENER_INIT}"
	installSysconfigScript "jsonListener" "${LISTENER_SYSCONFIG}"

	case "${PLATFORM}" in
	'SLES') $DRYRUN || insserv jsonListener;;
	'RHEL') $DRYRUN || chkconfig --add jsonListener;;
	*) echo "Unsupported platform"; exit 1;;
	esac
}

uninstallJsonListener()
{
	uninstallInitScript "jsonListener"
	uninstallSysconfigScript "jsonListener"
}

# Install init script
# $1 -- the base name to be used when copied
# $2 -- the path to the init script to be copied
# Return Codes
# 0 -- success
# 1 -- error
installInitScript()
{
	copyFileTo "${2}" "${INIT_DIR}/${1}" 755 "root:root"
	if [ "${PLATFORM}" == 'SLES' ]; then
		DEBUG echo ln -s "${INIT_DIR}/${1}" "${SBIN_DIR}/rc${1}"
		$DRYRUN || ln -s "${INIT_DIR}/${1}" "${SBIN_DIR}/rc${1}"
	fi
	return 0
}

# Verify init script
# Arguments
# $1 -- the base name of the init script
verifyInitScript()
{
	verifyFile "${INIT_DIR}/${1}" 755 "root" "root"
	verifyFile "${SYSCONFIG_DIR}/${1}" 644 "root" "root"
}


# $1 -- the base name of the init script
uninstallInitScript()
{
	DEBUG echo rm "${INIT_DIR}/${1}"
	$DRYRUN || rm "${INIT_DIR}/${1}"
	if [ "${PLATFORM}" == 'SLES' ]; then
		DEBUG echo rm "/sbin/rc${1}"
		$DRYRUN || rm "/sbin/rc${1}"
	fi
}

# Install sysconfig script
# $1 -- the base name of the sysconfig script
# $1 -- the path to the sysconfig script to be copied
installSysconfigScript()
{
	copyFileTo "${2}" "${SYSCONFIG_DIR}/${1}" 644 "root:root"
}

# Uninstall sysconfig script
# $1 -- the base name of the sysconfig script
uninstallSysconfigScript()
{
	DEBUG echo rm "${SYSCONFIG_DIR}/${1}"
	$DRYRUN || rm "${SYSCONFIG_DIR}/${1}"
}

case "${MODE}" in
install )
	case "${PRODUCT}" in
	informix ) installInformix;;
	jsonListener ) installJsonListener;;
	* ) echo "Unsupport product ${PRODUCT}"; exit 1;;
	esac
	;;
uninstall )
	case "${PRODUCT}" in
	informix ) uninstallInformix;;
	jsonListener ) uninstallJsonListener;;
	* ) echo "Unsupport product ${PRODUCT}"; exit 1;;
	esac
	;;
verify )
	case "${PRODUCT}" in
	informix ) verifyInitScript "informix";;
	jsonListener ) verifyInitScript "jsonListener";;
	* ) echo "Unsupport product ${PRODUCT}"; exit 1;;
	esac
	;;
* )
	echo "Must specify --install, --uninstall, or --verify";
	usage
	exit 1;
	;;
esac

