#!/bin/bash

dbaccess sysmaster <<!
select  name[1,8] dbspace,              -- name truncated to fit on one line
	sum(chksize) Pages_size,        -- sum of all chunks size pages
	sum(chksize) - sum(nfree) Pages_used,
	sum(nfree) Pages_free,          -- sum of all chunks free pages
	round ((sum(nfree)) / (sum(chksize)) * 100, 2) percent_free
from    sysdbspaces d, syschunks c
where   d.dbsnum = c.dbsnum
group by 1
order by 1;
!
