#!/bin/bash

# chkflist.sql - display list of free space within a chunk

dbaccess sysmaster <<!
select  
	name dbspace,      -- dbspace name truncated to fit
	f.chknum,          -- chunk number
	f.extnum,          -- extent number of free space
	f.start,           -- starting address of free space
	f.leng free_pages  -- length of free space
from sysdbspaces d, syschunks c, syschfree f
where d.dbsnum = c.dbsnum
and c.chknum = f.chknum
order by dbspace, chknum
!
